### ISSUE TITLE
Feature: custom sort

### ISSUE THREAD

**Issue by kvernon** [valeriangalliat/pretty-package-json#1]
Howdy!

This is a pretty nice little tool, but is there a way to customize the sort? 

Essentially, I'd like to include the $schema, and leave it at the top. However, I'm sure some people may want a little more flex.

**Comment by valeriangalliat** [comment]
Hey! Glad you like this tool, I really thought I was alone being that nitpicky about my `package.json` files. 😂 

There's currently no way to customize the sort order, but I believe `$schema` is to reference a JSON Schema for validation, e.g. [from Schema Store](https://www.schemastore.org/json/)? That sounds standard enough to just include it in the list.

I added it as part of v1.0.0 (figured it was about time to go out of development versions :tada:).

If there's a need to support more custom / less standard keys in the future, we can look at adding a configuration file then.

Cheers!
